version: '3.1'

services:
  punchcard:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
    ports:
      - "3307:3306"
    volumes:
      - ./mysql/image:/docker-entrypoint-initdb.d
  enigma:
    build: .
    depends_on:
      - punchcard
    ports:
      - "8081:8080"