version: '3'
services:
  server:
    build: ./backend/enigma/
    env_file:
      - ./backend/enigma/.env
    expose:
      - "8080"
    restart: always

    # Add any additional configuration for the server service

  client:
    build: ./web/
    env_file:
      - ./web/.env.development
    expose:
      - "3000"
    restart: always
    # Add any additional configuration for the client service

  front:
    image: nginx
    depends_on:
      - server
      - client
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/.well-known:/usr/share/nginx/html/
      - ./nginx/default.conf:/etc/nginx/conf.d/
    restart: always