version: '3'
services:

  enigma-db:
    image: mysql:latest
    restart: always
    env_file:
      - ./backend/enigma/.env
    volumes:
      - enigma_data:/var/lib/mysql
    ports:
      - "3306:3306"  # Expose port for MySQL

  annotation-db:
    image: mysql:latest
    restart: always
    env_file:
      - ./backend/annotation/.env
    volumes:
      - annotation_data:/var/lib/mysql
    ports:
      - "3307:3306"  # Expose port for MySQL

  enigma-server:
    build: ./backend/enigma/
    env_file:
      - ./backend/enigma/.env
    expose:
      - "8080:8080"
    restart: always
    depends_on:
      - enigma-db

  annotation-server:
    build: ./backend/annotation/
    env_file:
      - ./backend/annotation/.env
    expose:
      - "8081:8080"
    restart: always
    depends_on:
      - annotation-db

  client:
    build: ./web/
    env_file:
      - ./web/.env.development
    expose:
      - "3000:3000"
    restart: always

  web-server:
    image: nginx
    depends_on:
      - enigma-server
      - client
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/.well-known:/usr/share/nginx/html/
      - ./nginx/:/etc/nginx/conf.d/
    restart: always

volumes:
  enigma_data:  # This defines the named volume
  annotation_data:
